# Generated by Django 3.2.4 on 2021-06-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='Username',
            new_name='username',
        ),
    ]
