# Generated by Django 3.2.4 on 2021-06-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_rename_username_userdata_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Userdata',
            new_name='User',
        ),
    ]
